#!/usr/bin/env python3

# Walker Bagley and Patrick Schlosser
# CSE 30151: Theory of Computing CP4
# 21 April 2023

import sys
# import re_to_nfa as re
import nfa
import parse_re
import regexp

if __name__=='__main__':
    # couldn't get this any lower
    sys.setrecursionlimit(2250)

    tree = regexp.parse(sys.argv[1])
    n = regexp.to_nfa(tree)
    # print(tree)

    # n = re.re_to_nfa(sys.argv[1])
    for line in sys.stdin:
        if nfa.match_dfs(n, line.strip())[0]:
            print(line)